# Generated by Django 4.0.5 on 2022-08-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_document_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='color',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='image_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='medium',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='record_type',
            field=models.TextField(blank=True),
        ),
    ]
