# Generated by Django 4.0.5 on 2022-08-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_archivedocument_color_archivedocument_image_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedocument',
            name='color',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archivedocument',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archivedocument',
            name='image_content',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archivedocument',
            name='medium',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archivedocument',
            name='record_type',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
