# Generated by Django 4.0.5 on 2022-08-08 04:17

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_remove_archivedocument_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photograph',
            name='creator',
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='creator',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='archivedocument',
            name='photo_image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='photographs/', variations={'thumbnail': {'height': 300, 'width': 300}}),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='image_content',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='record_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
